quarkus.http.host=0.0.0.0
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-delicate-lab-alg06571-pooler.c-3.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_zKV9RuOSE6kH&sslmode=require&channelBinding=require
quarkus.hibernate-orm.database.generation=update